### PR TITLE
Transport updates

### PR DESCRIPTION
**Pull request by Reldnahc**
add magic spell support to transport
add portal nexus support (still in progress needs to explore the house a little)
add house portal tablets
add some skillscapes

remove troll stronghold agility shortcut tele cuz it doesn't work

### CODE REVIEW

**Comment by Reldnahc** [comment]
@MilesWilde

**Comment by Torwent** [comment]
Looks good. Can I merge @MilesWilde ?

**Comment by Reldnahc** [comment]
Not yet! using this to get a nice diff and plan a little more before merge

**Comment by Torwent** [comment]
Okay let me know, I'll @skunks in discord when you are done if he doesn't reply until then

**Comment by Torwent** [comment]
btw, careful with breaking things for others. wasplib now has a simple tool to test compile scripts

**Comment by MilesWilde** [comment]
looks good to me

**Pull request merged**
