### PR TITLE
Update waspweb.graph

### PR DESCRIPTION
**Pull request by Reldnahc**
add fossil island loom

### CODE REVIEW

**Comment by Reldnahc** [comment]
Accidentally uploaded a graph that also has this but probs don't hurt to also include it.
image

**Comment by Torwent** [comment]
I would like all os the map completed so every addition is welcome. thank you!

**Comment by Reldnahc** [comment]
image

**Comment by Torwent** [comment]
so is it ready?

**Comment by Reldnahc** [comment]
yes, it's ready now I mapped out what my scripts will want. If you think any more spots would be useful to have mapped I can spend the time to do it I don't mind.

**Comment by Torwent** [comment]
No worries, just add things as you need them!
thank you

**Pull request merged**
