### PR TITLE
Rune fountain webwalking + mapping

### PR DESCRIPTION
**Pull request by bainwc**
I hope I did things right, tried to follow as many instructions as I found for this pull request thing. I've added webwalking using the webber for Rune Fountain in wildy and I also made smaller maps for the fountain and edge bank in RSRegions. I am hoping to post a glory charging script to the discord once I'm done.

### CODE REVIEW

**Comment by Torwent** [comment]
Hey! Thanks for the PR.
I might be missing something but I don't see any change to the webgraph? What did you change exactly?
Also, as for the RSRegions added, the EDGEBANK once seems very unnecessary. Just use the EDGEVILLE one which shouldn't even exist either to be honest since there's so much in that area in the first place but just use that one. If you really need a smaller box use the box directly.

**Comment by bainwc** [comment]
Thanks! I just assumed the smaller map was better for loading but I'll use EDGEVILLE instead. As for the webgraph, I created a web with webber and I believe it saved properly at line 125 and 302. They now have RuneFountain and   Self.RUNEFOUNTAIN := [8633, 797], respectively.

**Comment by Torwent** [comment]
Loading a smaller box is more performant yes but it will not be noticeable st all in this case where the difference in size is not that big. You also get the risk of accidentally walking outside it and get completely lost.
If for some reason you really need that extra performance, you can always just use the box directly in walker.

It does not, the webgraph seems to be unchanged.
But don't worry, I'll add it soon.

**Comment by Torwent** [comment]
Alright, this is added! :)

**Pull request closed without merging**
